# Site settings
title: warpbreaks
email: ralph.schlosser@gmail.com
description: >
  Data and Code
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.warpbreaks.io" # the base hostname & protocol for your site
#twitter_username: anildigital
github_username:  bwv988

# Build settings
markdown: kramdown
