# Site settings
title: warpbreaks.io
email: ralph.schlosser@gmail.com
description: )---> Data, Code and Stuff <---(
baseurl: ""
url: "http://www.warpbreaks.io"
#twitter_username: anildigital
github_username:  bwv988

# Build settings
markdown: kramdown
